package fr.nomapech.literia.init;

import fr.nomapech.literia.objects.items.ArmorItem;
import fr.nomapech.literia.objects.items.AxeItem;
import fr.nomapech.literia.objects.items.BasicItem;
import fr.nomapech.literia.objects.items.BowItem;
import fr.nomapech.literia.objects.items.DynamiteItem;
import fr.nomapech.literia.objects.items.HammerItem;
import fr.nomapech.literia.objects.items.HoeItem;
import fr.nomapech.literia.objects.items.PickaxeItem;
import fr.nomapech.literia.objects.items.ShearsItem;
import fr.nomapech.literia.objects.items.ShovelItem;
import fr.nomapech.literia.objects.items.StickItem;
import fr.nomapech.literia.objects.items.SwordItem;
import fr.nomapech.literia.objects.items.UnclaimFinderItem;
import java.util.ArrayList;
import java.util.List;

import net.minecraft.inventory.EntityEquipmentSlot;
import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor;
import net.minecraft.item.ItemBow;
import net.minecraft.item.ItemHoe;
import net.minecraft.item.ItemPickaxe;
import net.minecraft.item.ItemShears;
import net.minecraft.item.ItemSpade;
import net.minecraft.item.ItemSword;

public class ItemsInit {
   public static List ITEMS = new ArrayList();
   public static Item COPPER = new BasicItem("copper");
   public static ItemSword COPPER_SWORD;
   public static ItemPickaxe COPPER_PICKAXE;
   public static AxeItem COPPER_AXE;
   public static ItemSpade COPPER_SHOVEL;
   public static ItemArmor COPPER_HELMET;
   public static ItemArmor COPPER_CHESTPLATE;
   public static ItemArmor COPPER_LEGGING;
   public static ItemArmor COPPER_BOOTS;
   public static Item TIN;
   public static ItemSword TIN_SWORD;
   public static ItemPickaxe TIN_PICKAXE;
   public static AxeItem TIN_AXE;
   public static ItemSpade TIN_SHOVEL;
   public static ItemArmor TIN_HELMET;
   public static ItemArmor TIN_CHESTPLATE;
   public static ItemArmor TIN_LEGGING;
   public static ItemArmor TIN_BOOTS;
   public static Item ISOLUA;
   public static ItemSword ISOLUA_SWORD;
   public static ItemPickaxe ISOLUA_PICKAXE;
   public static AxeItem ISOLUA_AXE;
   public static ItemSpade ISOLUA_SHOVEL;
   public static ItemPickaxe ISOLUA_HAMMER;
   public static ItemArmor ISOLUA_HELMET;
   public static ItemArmor ISOLUA_CHESTPLATE;
   public static ItemArmor ISOLUA_LEGGING;
   public static ItemArmor ISOLUA_BOOTS;
   public static Item LITERIUM;
   public static ItemSword LITERIUM_SWORD;
   public static ItemPickaxe LITERIUM_PICKAXE;
   public static AxeItem LITERIUM_AXE;
   public static ItemSpade LITERIUM_SHOVEL;
   public static ItemHoe LITERIUM_HOE;
   public static ItemPickaxe LITERIUM_HAMMER;
   public static ItemShears LITERIUM_SHEARS;
   public static ItemBow LITERIUM_BOW;
   public static ItemArmor LITERIUM_HELMET;
   public static ItemArmor LITERIUM_CHESTPLATE;
   public static ItemArmor LITERIUM_LEGGING;
   public static ItemArmor LITERIUM_BOOTS;
   public static Item LITERIUM_STICK;
   public static Item DEMONITE;
   public static ItemSword DEMONITE_SWORD;
   public static ItemPickaxe DEMONITE_PICKAXE;
   public static AxeItem DEMONITE_AXE;
   public static ItemSpade DEMONITE_SHOVEL;
   public static ItemBow DEMONITE_BOW;
   public static ItemArmor DEMONITE_HELMET;
   public static ItemArmor DEMONITE_CHESTPLATE;
   public static ItemArmor DEMONITE_LEGGING;
   public static ItemArmor DEMONITE_BOOTS;
   public static Item DEMONITE_STICK;
   public static Item HEAL_ORB;
   public static Item SPEED_ORB;
   public static Item STRENGHT_ORB;
   public static Item LEGENDARY_ORB;
   public static Item HEAL_STICK;
   public static Item SPEED_STICK;
   public static Item STRENGHT_STICK;
   public static Item LEGENDARY_STICK;
   public static Item UNCLAIM_FINDER_LVL_1;
   public static Item UNCLAIM_FINDER_LVL_2;
   public static Item DYNAMITE;

   static {
      COPPER_SWORD = new SwordItem("copper_sword", ToolMaterialsInit.COPPER_TOOLS);
      COPPER_PICKAXE = new PickaxeItem("copper_pickaxe", ToolMaterialsInit.COPPER_TOOLS);
      COPPER_AXE = new AxeItem("copper_axe", ToolMaterialsInit.COPPER_TOOLS);
      COPPER_SHOVEL = new ShovelItem("copper_shovel", ToolMaterialsInit.COPPER_TOOLS);
      COPPER_HELMET = new ArmorItem("copper_helmet", ToolMaterialsInit.COPPER_ARMOR, 1, EntityEquipmentSlot.HEAD);
      COPPER_CHESTPLATE = new ArmorItem("copper_chestplate", ToolMaterialsInit.COPPER_ARMOR, 1, EntityEquipmentSlot.CHEST);
      COPPER_LEGGING = new ArmorItem("copper_legging", ToolMaterialsInit.COPPER_ARMOR, 2, EntityEquipmentSlot.LEGS);
      COPPER_BOOTS = new ArmorItem("copper_boots", ToolMaterialsInit.COPPER_ARMOR, 1, EntityEquipmentSlot.FEET);
      TIN = new BasicItem("tin");
      TIN_SWORD = new SwordItem("tin_sword", ToolMaterialsInit.TIN_TOOLS);
      TIN_PICKAXE = new PickaxeItem("tin_pickaxe", ToolMaterialsInit.TIN_TOOLS);
      TIN_AXE = new AxeItem("tin_axe", ToolMaterialsInit.TIN_TOOLS);
      TIN_SHOVEL = new ShovelItem("tin_shovel", ToolMaterialsInit.TIN_TOOLS);
      TIN_HELMET = new ArmorItem("tin_helmet", ToolMaterialsInit.TIN_ARMOR, 1, EntityEquipmentSlot.HEAD);
      TIN_CHESTPLATE = new ArmorItem("tin_chestplate", ToolMaterialsInit.TIN_ARMOR, 1, EntityEquipmentSlot.CHEST);
      TIN_LEGGING = new ArmorItem("tin_legging", ToolMaterialsInit.TIN_ARMOR, 2, EntityEquipmentSlot.LEGS);
      TIN_BOOTS = new ArmorItem("tin_boots", ToolMaterialsInit.TIN_ARMOR, 1, EntityEquipmentSlot.FEET);
      ISOLUA = new BasicItem("isolua");
      ISOLUA_SWORD = new SwordItem("isolua_sword", ToolMaterialsInit.ISOLUA_SWORD);
      ISOLUA_PICKAXE = new PickaxeItem("isolua_pickaxe", ToolMaterialsInit.ISOLUA_TOOLS);
      ISOLUA_AXE = new AxeItem("isolua_axe", ToolMaterialsInit.ISOLUA_TOOLS);
      ISOLUA_SHOVEL = new ShovelItem("isolua_shovel", ToolMaterialsInit.ISOLUA_SHOVEL);
      ISOLUA_HAMMER = new HammerItem("isolua_hammer", ToolMaterialsInit.ISOLUA_HAMMER);
      ISOLUA_HELMET = new ArmorItem("isolua_helmet", ToolMaterialsInit.ISOLUA_ARMOR, 1, EntityEquipmentSlot.HEAD);
      ISOLUA_CHESTPLATE = new ArmorItem("isolua_chestplate", ToolMaterialsInit.ISOLUA_ARMOR, 1, EntityEquipmentSlot.CHEST);
      ISOLUA_LEGGING = new ArmorItem("isolua_legging", ToolMaterialsInit.ISOLUA_ARMOR, 2, EntityEquipmentSlot.LEGS);
      ISOLUA_BOOTS = new ArmorItem("isolua_boots", ToolMaterialsInit.ISOLUA_ARMOR, 1, EntityEquipmentSlot.FEET);
      LITERIUM = new BasicItem("literium");
      LITERIUM_SWORD = new SwordItem("literium_sword", ToolMaterialsInit.LITERIUM_SWORD);
      LITERIUM_PICKAXE = new PickaxeItem("literium_pickaxe", ToolMaterialsInit.LITERIUM_PICKAXE);
      LITERIUM_AXE = new AxeItem("literium_axe", ToolMaterialsInit.LITERIUM_AXE);
      LITERIUM_SHOVEL = new ShovelItem("literium_shovel", ToolMaterialsInit.LITERIUM_SHOVEL);
      LITERIUM_HOE = new HoeItem("literium_hoe", ToolMaterialsInit.LITERIUM_HOE);
      LITERIUM_HAMMER = new HammerItem("literium_hammer", ToolMaterialsInit.LITERIUM_HAMMER);
      LITERIUM_SHEARS = new ShearsItem("literium_shears", 2000);
      LITERIUM_BOW = new BowItem("literium_bow", 751, 4.0D);
      LITERIUM_HELMET = new ArmorItem("literium_helmet", ToolMaterialsInit.LITERIUM_ARMOR, 1, EntityEquipmentSlot.HEAD);
      LITERIUM_CHESTPLATE = new ArmorItem("literium_chestplate", ToolMaterialsInit.LITERIUM_ARMOR, 1, EntityEquipmentSlot.CHEST);
      LITERIUM_LEGGING = new ArmorItem("literium_legging", ToolMaterialsInit.LITERIUM_ARMOR, 2, EntityEquipmentSlot.LEGS);
      LITERIUM_BOOTS = new ArmorItem("literium_boots", ToolMaterialsInit.LITERIUM_ARMOR, 1, EntityEquipmentSlot.FEET);
      LITERIUM_STICK = new BasicItem("literium_stick");
      DEMONITE = new BasicItem("demonite");
      DEMONITE_SWORD = new SwordItem("demonite_sword", ToolMaterialsInit.DEMONITE_SWORD);
      DEMONITE_PICKAXE = new PickaxeItem("demonite_pickaxe", ToolMaterialsInit.DEMONITE_PICKAXE);
      DEMONITE_AXE = new AxeItem("demonite_axe", ToolMaterialsInit.DEMONITE_AXE);
      DEMONITE_SHOVEL = new ShovelItem("demonite_shovel", ToolMaterialsInit.DEMONITE_SHOVEL);
      DEMONITE_BOW = new BowItem("demonite_bow", 1000, 4.0D);
      DEMONITE_HELMET = new ArmorItem("demonite_helmet", ToolMaterialsInit.DEMONITE_ARMOR, 1, EntityEquipmentSlot.HEAD);
      DEMONITE_CHESTPLATE = new ArmorItem("demonite_chestplate", ToolMaterialsInit.DEMONITE_ARMOR, 1, EntityEquipmentSlot.CHEST);
      DEMONITE_LEGGING = new ArmorItem("demonite_legging", ToolMaterialsInit.DEMONITE_ARMOR, 2, EntityEquipmentSlot.LEGS);
      DEMONITE_BOOTS = new ArmorItem("demonite_boots", ToolMaterialsInit.DEMONITE_ARMOR, 1, EntityEquipmentSlot.FEET);
      DEMONITE_STICK = new BasicItem("demonite_stick");
      HEAL_ORB = new BasicItem("heal_orb");
      SPEED_ORB = new BasicItem("speed_orb");
      STRENGHT_ORB = new BasicItem("strenght_orb");
      LEGENDARY_ORB = new BasicItem("legendary_orb");
      HEAL_STICK = new StickItem("heal_stick", 10);
      SPEED_STICK = new StickItem("speed_stick", 10);
      STRENGHT_STICK = new StickItem("strenght_stick", 10);
      LEGENDARY_STICK = new StickItem("legendary_stick", 10);
      UNCLAIM_FINDER_LVL_1 = new UnclaimFinderItem("unclaim_finder_lvl_1", 2160000);
      UNCLAIM_FINDER_LVL_2 = new UnclaimFinderItem("unclaim_finder_lvl_2", 1440000);
      DYNAMITE = new DynamiteItem("dynamite");
   }
}
